### ISSUE TITLE
disabled不生效嘛

### ISSUE THREAD

**Issue by spanull** [mezhanglei/react-free-draggable#1]

**Comment by mezhanglei** [comment]
disabled会阻止你进行点击拖拽，不知道你是如何使用的

**Comment by spanull** [comment]
你有两个拖拽组件我发现我看错文档了www，可以帮我删一下问题嘛



***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mezhanglei/react-free-draggable"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月22日(星期三) 中午1:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mezhanglei/react-free-draggable] disabled不生效嘛 (Issue #1)





 
disabled会阻止你进行点击拖拽，不知道你是如何使用的
